/**
 * Data-protection operations for the run store.
 *
 * Written against the revised Swiss Federal Act on Data Protection (revFADP /
 * revDSG, in force 1 September 2023). CiteBeam stores audit runs, which can
 * contain personal data: a sole trader's business name is their name, contact
 * details appear in crawled pages, and answer text can name individuals.
 *
 * The Act requires that data be kept only as long as the purpose needs
 * (Art. 6), that a data subject can obtain their data (Art. 25) and have it
 * erased (Art. 32), and that the controller can describe its processing.
 * These functions are the mechanics for honouring those requests; the
 * operator still owns the legal duty to answer them.
 *
 * This is engineering support for compliance, not legal advice.
 * @module store/privacy
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, rmSync, mkdirSync } from 'node:fs';
import path from 'node:path';

/** Default retention. Chosen so year-on-year comparison stays possible. */
export const DEFAULT_RETENTION_DAYS = Number(process.env.CITEBEAM_RETENTION_DAYS || 730);

/**
 * Delete runs older than the retention window.
 *
 * @param {import('./store.js').Store} store
 * @param {{days?:number, dryRun?:boolean}} [opts]
 * @returns {{removed:Array<{brand:string,id:string,createdAt:string}>, kept:number, cutoff:string}}
 */
export function purgeExpired(store, opts = {}) {
  const days = opts.days ?? DEFAULT_RETENTION_DAYS;
  const cutoff = new Date(Date.now() - days * 86400000);
  const removed = [];
  let kept = 0;

  for (const brand of store.brands()) {
    const dir = path.join(store.runsDir, brand.key);
    const index = store.history(brand.key);
    const survivors = [];

    for (const entry of index) {
      const at = new Date(entry.createdAt);
      const expired = Number.isFinite(at.getTime()) && at < cutoff;
      if (!expired) { survivors.push(entry); kept++; continue; }
      removed.push({ brand: brand.key, id: entry.id, createdAt: entry.createdAt });
      if (!opts.dryRun) {
        const file = path.join(dir, `${entry.id}.json`);
        if (existsSync(file)) rmSync(file, { force: true });
      }
    }

    if (!opts.dryRun && removed.length) {
      writeFileSync(path.join(dir, 'index.json'), JSON.stringify(survivors, null, 2));
      // A brand with no runs left should not linger as an empty shell.
      if (!survivors.length) rmSync(dir, { recursive: true, force: true });
    }
  }
  return { removed, kept, cutoff: cutoff.toISOString() };
}

/**
 * Export everything held about one brand, for a right-of-access request
 * (revFADP Art. 25). Written as a single JSON file the operator can hand over.
 *
 * @param {import('./store.js').Store} store
 * @param {string} brandKey
 * @param {string} outFile
 */
export function exportSubject(store, brandKey, outFile) {
  const history = store.history(brandKey);
  const runs = history.map((entry) => store.load(brandKey, entry.id)).filter(Boolean);
  const payload = {
    generatedAt: new Date().toISOString(),
    subject: brandKey,
    lawfulBasis: 'Audit performed under contract with the data subject or their agent.',
    retentionDays: DEFAULT_RETENTION_DAYS,
    runCount: runs.length,
    runs,
  };
  mkdirSync(path.dirname(path.resolve(outFile)), { recursive: true });
  writeFileSync(outFile, JSON.stringify(payload, null, 2));
  return { file: path.resolve(outFile), runCount: runs.length };
}

/**
 * Erase everything held about one brand (revFADP Art. 32).
 *
 * @param {import('./store.js').Store} store
 * @param {string} brandKey
 */
export function eraseSubject(store, brandKey) {
  const before = store.history(brandKey).length;
  store.remove(brandKey);
  return { brand: brandKey, runsDeleted: before };
}

/**
 * Describe what this deployment processes, so the operator can answer a
 * supervisory question or draft a privacy notice without reverse-engineering
 * the code. Values reflect the running configuration, not a static template.
 *
 * @param {import('./store.js').Store} store
 */
export function processingRegister(store) {
  const brands = store.brands();
  return {
    generatedAt: new Date().toISOString(),
    controller: process.env.CITEBEAM_CONTROLLER || '[set CITEBEAM_CONTROLLER to your legal entity]',
    contact: process.env.CITEBEAM_DPO_CONTACT || '[set CITEBEAM_DPO_CONTACT to your data contact]',
    purposes: [
      'Auditing whether a client brand appears in AI assistant answers.',
      'Auditing a client website\'s technical readiness for answer engines.',
      'Producing an advisory report for that client.',
    ],
    categories: [
      'Publicly published business website content.',
      'Business contact details found on those public pages.',
      'Text generated by third-party AI assistants in response to prompts about the category.',
    ],
    sources: ['The client\'s own website (public pages only)', 'Configured AI provider APIs'],
    recipients: [
      'Configured AI providers receive the prompt text, which contains the brand and '
      + 'category names supplied by the operator. No crawled page content is sent to them.',
    ],
    crossBorder: 'AI provider APIs are typically operated outside Switzerland. Confirm your '
      + 'provider\'s terms and transfer mechanism before processing client data.',
    storage: {
      location: store.dir,
      retentionDays: DEFAULT_RETENTION_DAYS,
      brandsHeld: brands.length,
      runsHeld: brands.reduce((n, b) => n + b.runs, 0),
    },
    subjectRights: {
      access: 'citebeam privacy export <domain> --out file.json',
      erasure: 'citebeam privacy erase <domain>',
    },
    note: 'Generated from the running configuration. It is a starting point for your records, '
      + 'not legal advice, and not a substitute for your own assessment.',
  };
}
